// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -971652086;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__activer_protection_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "activer_protection",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::EvenementMoteur,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::error::CleanXError>((move || {
                    let output_ok = crate::api::activer_protection(api_sink)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__ajouter_dossier_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ajouter_dossier",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_dossier = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::ajouter_dossier(api_dossier)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__ajouter_planification_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ajouter_planification",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_nom = <String>::sse_decode(&mut deserializer);
            let api_racines = <Vec<String>>::sse_decode(&mut deserializer);
            let api_intervalle_secs = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok =
                    crate::api::ajouter_planification(api_nom, api_racines, api_intervalle_secs)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__analyser_heuristique_api_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyser_heuristique_api",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_chemin = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::analyser_heuristique_api(api_chemin)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__analyser_processus_api_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyser_processus_api",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::analyser_processus_api()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__arreter_scan_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "arreter_scan",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::arreter_scan()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__calculer_sha256_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "calculer_sha256",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_chemin = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::calculer_sha256(api_chemin)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__deriver_cle_api_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "deriver_cle_api",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_phrase = <String>::sse_decode(&mut deserializer);
            let api_sel_b64 = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::deriver_cle_api(api_phrase, api_sel_b64)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__desactiver_protection_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "desactiver_protection",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::desactiver_protection()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__dossiers_surveilles_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "dossiers_surveilles",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::dossiers_surveilles()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__exporter_logs_csv_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "exporter_logs_csv",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::exporter_logs_csv()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__initialiser_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initialiser",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_base = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::initialiser(api_base)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__integrite_binaire_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "integrite_binaire",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::integrite_binaire()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__liberer_ressources_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "liberer_ressources",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::liberer_ressources()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__limites_rootkit_api_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "limites_rootkit_api",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::limites_rootkit_api()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__lister_logs_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "lister_logs",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_limite = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::lister_logs(api_limite)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__lister_planifications_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "lister_planifications",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::lister_planifications()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__lister_quarantaine_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "lister_quarantaine",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::lister_quarantaine()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__mettre_a_jour_signatures_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "mettre_a_jour_signatures",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_url_depot = <String>::sse_decode(&mut deserializer);
            let api_cle_publique_hex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::error::CleanXError>(
                    (move || async move {
                        let output_ok = crate::api::mettre_a_jour_signatures(
                            api_url_depot,
                            api_cle_publique_hex,
                        )
                        .await?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__mettre_en_quarantaine_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "mettre_en_quarantaine",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_chemin = <String>::sse_decode(&mut deserializer);
            let api_raison = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::mettre_en_quarantaine(api_chemin, api_raison)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__mode_jeu_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "mode_jeu",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_actif = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::mode_jeu(api_actif)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__mode_jeu_actif_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "mode_jeu_actif",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::mode_jeu_actif()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__restaurer_quarantaine_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "restaurer_quarantaine",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <i64>::sse_decode(&mut deserializer);
            let api_destination = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::restaurer_quarantaine(api_id, api_destination)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__retirer_dossier_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "retirer_dossier",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_dossier = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::retirer_dossier(api_dossier)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__scan_complet_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "scan_complet",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::EvenementMoteur,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::error::CleanXError>((move || {
                    let output_ok = crate::api::scan_complet(api_sink)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__scan_personnalise_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "scan_personnalise",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_racines = <Vec<String>>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::EvenementMoteur,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::error::CleanXError>((move || {
                    let output_ok = crate::api::scan_personnalise(api_racines, api_sink)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__scan_rapide_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "scan_rapide",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::EvenementMoteur,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::error::CleanXError>((move || {
                    let output_ok = crate::api::scan_rapide(api_sink)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__statut_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "statut",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::statut()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__supprimer_planification_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "supprimer_planification",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::supprimer_planification(api_id)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__supprimer_quarantaine_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "supprimer_quarantaine",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::supprimer_quarantaine(api_id)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__suspendre_scan_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "suspendre_scan",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_suspendre = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::suspendre_scan(api_suspendre)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__verifier_integrite_api_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "verifier_integrite_api",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_attendu = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::verifier_integrite_api(api_attendu)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__verifier_paquet_api_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "verifier_paquet_api",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_paquet = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_signature_hex = <String>::sse_decode(&mut deserializer);
            let api_cle_publique_hex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::CleanXError>((move || {
                let output_ok = crate::api::verifier_paquet_api(
                    api_paquet,
                    api_signature_hex,
                    api_cle_publique_hex,
                )?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::EvenementMoteur, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::heuristics::AnalyseHeuristique {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_score = <u8>::sse_decode(deserializer);
        let mut var_signaux = <Vec<String>>::sse_decode(deserializer);
        let mut var_verdict = <crate::heuristics::VerdictHeuristique>::sse_decode(deserializer);
        return crate::heuristics::AnalyseHeuristique {
            score: var_score,
            signaux: var_signaux,
            verdict: var_verdict,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::error::CleanXError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::error::CleanXError::MoteurNonInitialise;
            }
            1 => {
                let mut var_chemin = <String>::sse_decode(deserializer);
                return crate::error::CleanXError::FichierIntrouvable { chemin: var_chemin };
            }
            2 => {
                let mut var_chemin = <String>::sse_decode(deserializer);
                let mut var_detail = <String>::sse_decode(deserializer);
                return crate::error::CleanXError::PermissionRefusee {
                    chemin: var_chemin,
                    detail: var_detail,
                };
            }
            3 => {
                let mut var_chemin = <String>::sse_decode(deserializer);
                return crate::error::CleanXError::FichierVerrouille { chemin: var_chemin };
            }
            4 => {
                let mut var_chemin = <String>::sse_decode(deserializer);
                return crate::error::CleanXError::CheminInvalide { chemin: var_chemin };
            }
            5 => {
                let mut var_detail = <String>::sse_decode(deserializer);
                return crate::error::CleanXError::BaseCorrompue { detail: var_detail };
            }
            6 => {
                let mut var_detail = <String>::sse_decode(deserializer);
                return crate::error::CleanXError::Quarantaine { detail: var_detail };
            }
            7 => {
                let mut var_detail = <String>::sse_decode(deserializer);
                return crate::error::CleanXError::CoffreIndisponible { detail: var_detail };
            }
            8 => {
                let mut var_detail = <String>::sse_decode(deserializer);
                return crate::error::CleanXError::Surveillance { detail: var_detail };
            }
            9 => {
                return crate::error::CleanXError::ScanAnnule;
            }
            10 => {
                return crate::error::CleanXError::ScanDejaEnCours;
            }
            11 => {
                let mut var_detail = <String>::sse_decode(deserializer);
                return crate::error::CleanXError::NonSupporte { detail: var_detail };
            }
            12 => {
                let mut var_detail = <String>::sse_decode(deserializer);
                return crate::error::CleanXError::Interne { detail: var_detail };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::logging::EntreeLog {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_date = <String>::sse_decode(deserializer);
        let mut var_niveau = <String>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        return crate::logging::EntreeLog {
            id: var_id,
            date: var_date,
            niveau: var_niveau,
            message: var_message,
        };
    }
}

impl SseDecode for crate::api::EvenementMoteur {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::EvenementMoteur::Journal {
                    message: var_message,
                };
            }
            1 => {
                let mut var_scanId = <String>::sse_decode(deserializer);
                let mut var_fichier = <String>::sse_decode(deserializer);
                let mut var_traites = <u64>::sse_decode(deserializer);
                let mut var_total = <u64>::sse_decode(deserializer);
                return crate::api::EvenementMoteur::Progression {
                    scan_id: var_scanId,
                    fichier: var_fichier,
                    traites: var_traites,
                    total: var_total,
                };
            }
            2 => {
                let mut var_fichier = <String>::sse_decode(deserializer);
                let mut var_menace = <String>::sse_decode(deserializer);
                let mut var_action = <String>::sse_decode(deserializer);
                let mut var_sha256 = <Option<String>>::sse_decode(deserializer);
                return crate::api::EvenementMoteur::Menace {
                    fichier: var_fichier,
                    menace: var_menace,
                    action: var_action,
                    sha256: var_sha256,
                };
            }
            3 => {
                let mut var_scanId = <String>::sse_decode(deserializer);
                let mut var_total = <u64>::sse_decode(deserializer);
                let mut var_menaces = <u64>::sse_decode(deserializer);
                let mut var_annule = <bool>::sse_decode(deserializer);
                return crate::api::EvenementMoteur::ScanTermine {
                    scan_id: var_scanId,
                    total: var_total,
                    menaces: var_menaces,
                    annule: var_annule,
                };
            }
            4 => {
                let mut var_active = <bool>::sse_decode(deserializer);
                return crate::api::EvenementMoteur::Protection { active: var_active };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::quarantine::FichierQuarantaine {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_nom = <String>::sse_decode(deserializer);
        let mut var_origine = <String>::sse_decode(deserializer);
        let mut var_date = <String>::sse_decode(deserializer);
        let mut var_raison = <String>::sse_decode(deserializer);
        let mut var_score = <u8>::sse_decode(deserializer);
        return crate::quarantine::FichierQuarantaine {
            id: var_id,
            nom: var_nom,
            origine: var_origine,
            date: var_date,
            raison: var_raison,
            score: var_score,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::logging::EntreeLog> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::logging::EntreeLog>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::quarantine::FichierQuarantaine> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::quarantine::FichierQuarantaine>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::scheduler::Planification> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::scheduler::Planification>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::rootkit::ProcessusAnalyse> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::rootkit::ProcessusAnalyse>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::scheduler::Planification {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_nom = <String>::sse_decode(deserializer);
        let mut var_racines = <Vec<String>>::sse_decode(deserializer);
        let mut var_intervalleSecs = <u64>::sse_decode(deserializer);
        let mut var_prochaineExec = <u64>::sse_decode(deserializer);
        return crate::scheduler::Planification {
            id: var_id,
            nom: var_nom,
            racines: var_racines,
            intervalle_secs: var_intervalleSecs,
            prochaine_exec: var_prochaineExec,
        };
    }
}

impl SseDecode for crate::rootkit::ProcessusAnalyse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_pid = <u32>::sse_decode(deserializer);
        let mut var_nom = <String>::sse_decode(deserializer);
        let mut var_exe = <Option<String>>::sse_decode(deserializer);
        let mut var_memoire = <u64>::sse_decode(deserializer);
        let mut var_signaux = <Vec<String>>::sse_decode(deserializer);
        return crate::rootkit::ProcessusAnalyse {
            pid: var_pid,
            nom: var_nom,
            exe: var_exe,
            memoire: var_memoire,
            signaux: var_signaux,
        };
    }
}

impl SseDecode for crate::api::StatutGlobal {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_protection = <bool>::sse_decode(deserializer);
        let mut var_signatures = <u32>::sse_decode(deserializer);
        let mut var_menaces = <u64>::sse_decode(deserializer);
        let mut var_fichiersAnalyses = <u64>::sse_decode(deserializer);
        let mut var_scanEnCours = <bool>::sse_decode(deserializer);
        let mut var_dossiers = <Vec<String>>::sse_decode(deserializer);
        return crate::api::StatutGlobal {
            protection: var_protection,
            signatures: var_signatures,
            menaces: var_menaces,
            fichiers_analyses: var_fichiersAnalyses,
            scan_en_cours: var_scanEnCours,
            dossiers: var_dossiers,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::heuristics::VerdictHeuristique {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::heuristics::VerdictHeuristique::Sain,
            1 => crate::heuristics::VerdictHeuristique::Suspect,
            2 => crate::heuristics::VerdictHeuristique::Menace,
            _ => unreachable!("Invalid variant for VerdictHeuristique: {}", inner),
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__activer_protection_impl(port, ptr, rust_vec_len, data_len),
        19 => wire__crate__api__mettre_a_jour_signatures_impl(port, ptr, rust_vec_len, data_len),
        25 => wire__crate__api__scan_complet_impl(port, ptr, rust_vec_len, data_len),
        26 => wire__crate__api__scan_personnalise_impl(port, ptr, rust_vec_len, data_len),
        27 => wire__crate__api__scan_rapide_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        2 => wire__crate__api__ajouter_dossier_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__ajouter_planification_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__analyser_heuristique_api_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__analyser_processus_api_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__arreter_scan_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__calculer_sha256_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__deriver_cle_api_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__desactiver_protection_impl(ptr, rust_vec_len, data_len),
        10 => wire__crate__api__dossiers_surveilles_impl(ptr, rust_vec_len, data_len),
        11 => wire__crate__api__exporter_logs_csv_impl(ptr, rust_vec_len, data_len),
        12 => wire__crate__api__initialiser_impl(ptr, rust_vec_len, data_len),
        13 => wire__crate__api__integrite_binaire_impl(ptr, rust_vec_len, data_len),
        14 => wire__crate__api__liberer_ressources_impl(ptr, rust_vec_len, data_len),
        15 => wire__crate__api__limites_rootkit_api_impl(ptr, rust_vec_len, data_len),
        16 => wire__crate__api__lister_logs_impl(ptr, rust_vec_len, data_len),
        17 => wire__crate__api__lister_planifications_impl(ptr, rust_vec_len, data_len),
        18 => wire__crate__api__lister_quarantaine_impl(ptr, rust_vec_len, data_len),
        20 => wire__crate__api__mettre_en_quarantaine_impl(ptr, rust_vec_len, data_len),
        21 => wire__crate__api__mode_jeu_impl(ptr, rust_vec_len, data_len),
        22 => wire__crate__api__mode_jeu_actif_impl(ptr, rust_vec_len, data_len),
        23 => wire__crate__api__restaurer_quarantaine_impl(ptr, rust_vec_len, data_len),
        24 => wire__crate__api__retirer_dossier_impl(ptr, rust_vec_len, data_len),
        28 => wire__crate__api__statut_impl(ptr, rust_vec_len, data_len),
        29 => wire__crate__api__supprimer_planification_impl(ptr, rust_vec_len, data_len),
        30 => wire__crate__api__supprimer_quarantaine_impl(ptr, rust_vec_len, data_len),
        31 => wire__crate__api__suspendre_scan_impl(ptr, rust_vec_len, data_len),
        32 => wire__crate__api__verifier_integrite_api_impl(ptr, rust_vec_len, data_len),
        33 => wire__crate__api__verifier_paquet_api_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::heuristics::AnalyseHeuristique {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.score.into_into_dart().into_dart(),
            self.signaux.into_into_dart().into_dart(),
            self.verdict.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::heuristics::AnalyseHeuristique
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::heuristics::AnalyseHeuristique>
    for crate::heuristics::AnalyseHeuristique
{
    fn into_into_dart(self) -> crate::heuristics::AnalyseHeuristique {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::error::CleanXError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::error::CleanXError::MoteurNonInitialise => [0.into_dart()].into_dart(),
            crate::error::CleanXError::FichierIntrouvable { chemin } => {
                [1.into_dart(), chemin.into_into_dart().into_dart()].into_dart()
            }
            crate::error::CleanXError::PermissionRefusee { chemin, detail } => [
                2.into_dart(),
                chemin.into_into_dart().into_dart(),
                detail.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::error::CleanXError::FichierVerrouille { chemin } => {
                [3.into_dart(), chemin.into_into_dart().into_dart()].into_dart()
            }
            crate::error::CleanXError::CheminInvalide { chemin } => {
                [4.into_dart(), chemin.into_into_dart().into_dart()].into_dart()
            }
            crate::error::CleanXError::BaseCorrompue { detail } => {
                [5.into_dart(), detail.into_into_dart().into_dart()].into_dart()
            }
            crate::error::CleanXError::Quarantaine { detail } => {
                [6.into_dart(), detail.into_into_dart().into_dart()].into_dart()
            }
            crate::error::CleanXError::CoffreIndisponible { detail } => {
                [7.into_dart(), detail.into_into_dart().into_dart()].into_dart()
            }
            crate::error::CleanXError::Surveillance { detail } => {
                [8.into_dart(), detail.into_into_dart().into_dart()].into_dart()
            }
            crate::error::CleanXError::ScanAnnule => [9.into_dart()].into_dart(),
            crate::error::CleanXError::ScanDejaEnCours => [10.into_dart()].into_dart(),
            crate::error::CleanXError::NonSupporte { detail } => {
                [11.into_dart(), detail.into_into_dart().into_dart()].into_dart()
            }
            crate::error::CleanXError::Interne { detail } => {
                [12.into_dart(), detail.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::error::CleanXError {}
impl flutter_rust_bridge::IntoIntoDart<crate::error::CleanXError> for crate::error::CleanXError {
    fn into_into_dart(self) -> crate::error::CleanXError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::logging::EntreeLog {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.date.into_into_dart().into_dart(),
            self.niveau.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::logging::EntreeLog {}
impl flutter_rust_bridge::IntoIntoDart<crate::logging::EntreeLog> for crate::logging::EntreeLog {
    fn into_into_dart(self) -> crate::logging::EntreeLog {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::EvenementMoteur {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::EvenementMoteur::Journal { message } => {
                [0.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::EvenementMoteur::Progression {
                scan_id,
                fichier,
                traites,
                total,
            } => [
                1.into_dart(),
                scan_id.into_into_dart().into_dart(),
                fichier.into_into_dart().into_dart(),
                traites.into_into_dart().into_dart(),
                total.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::EvenementMoteur::Menace {
                fichier,
                menace,
                action,
                sha256,
            } => [
                2.into_dart(),
                fichier.into_into_dart().into_dart(),
                menace.into_into_dart().into_dart(),
                action.into_into_dart().into_dart(),
                sha256.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::EvenementMoteur::ScanTermine {
                scan_id,
                total,
                menaces,
                annule,
            } => [
                3.into_dart(),
                scan_id.into_into_dart().into_dart(),
                total.into_into_dart().into_dart(),
                menaces.into_into_dart().into_dart(),
                annule.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::EvenementMoteur::Protection { active } => {
                [4.into_dart(), active.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::EvenementMoteur {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::EvenementMoteur>
    for crate::api::EvenementMoteur
{
    fn into_into_dart(self) -> crate::api::EvenementMoteur {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::quarantine::FichierQuarantaine {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.nom.into_into_dart().into_dart(),
            self.origine.into_into_dart().into_dart(),
            self.date.into_into_dart().into_dart(),
            self.raison.into_into_dart().into_dart(),
            self.score.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::quarantine::FichierQuarantaine
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::quarantine::FichierQuarantaine>
    for crate::quarantine::FichierQuarantaine
{
    fn into_into_dart(self) -> crate::quarantine::FichierQuarantaine {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::scheduler::Planification {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.nom.into_into_dart().into_dart(),
            self.racines.into_into_dart().into_dart(),
            self.intervalle_secs.into_into_dart().into_dart(),
            self.prochaine_exec.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::scheduler::Planification
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::scheduler::Planification>
    for crate::scheduler::Planification
{
    fn into_into_dart(self) -> crate::scheduler::Planification {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::rootkit::ProcessusAnalyse {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.pid.into_into_dart().into_dart(),
            self.nom.into_into_dart().into_dart(),
            self.exe.into_into_dart().into_dart(),
            self.memoire.into_into_dart().into_dart(),
            self.signaux.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::rootkit::ProcessusAnalyse
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::rootkit::ProcessusAnalyse>
    for crate::rootkit::ProcessusAnalyse
{
    fn into_into_dart(self) -> crate::rootkit::ProcessusAnalyse {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::StatutGlobal {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.protection.into_into_dart().into_dart(),
            self.signatures.into_into_dart().into_dart(),
            self.menaces.into_into_dart().into_dart(),
            self.fichiers_analyses.into_into_dart().into_dart(),
            self.scan_en_cours.into_into_dart().into_dart(),
            self.dossiers.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::StatutGlobal {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::StatutGlobal> for crate::api::StatutGlobal {
    fn into_into_dart(self) -> crate::api::StatutGlobal {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::heuristics::VerdictHeuristique {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Sain => 0.into_dart(),
            Self::Suspect => 1.into_dart(),
            Self::Menace => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::heuristics::VerdictHeuristique
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::heuristics::VerdictHeuristique>
    for crate::heuristics::VerdictHeuristique
{
    fn into_into_dart(self) -> crate::heuristics::VerdictHeuristique {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::EvenementMoteur, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::heuristics::AnalyseHeuristique {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.score, serializer);
        <Vec<String>>::sse_encode(self.signaux, serializer);
        <crate::heuristics::VerdictHeuristique>::sse_encode(self.verdict, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::error::CleanXError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::error::CleanXError::MoteurNonInitialise => {
                <i32>::sse_encode(0, serializer);
            }
            crate::error::CleanXError::FichierIntrouvable { chemin } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(chemin, serializer);
            }
            crate::error::CleanXError::PermissionRefusee { chemin, detail } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(chemin, serializer);
                <String>::sse_encode(detail, serializer);
            }
            crate::error::CleanXError::FichierVerrouille { chemin } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(chemin, serializer);
            }
            crate::error::CleanXError::CheminInvalide { chemin } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(chemin, serializer);
            }
            crate::error::CleanXError::BaseCorrompue { detail } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(detail, serializer);
            }
            crate::error::CleanXError::Quarantaine { detail } => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(detail, serializer);
            }
            crate::error::CleanXError::CoffreIndisponible { detail } => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(detail, serializer);
            }
            crate::error::CleanXError::Surveillance { detail } => {
                <i32>::sse_encode(8, serializer);
                <String>::sse_encode(detail, serializer);
            }
            crate::error::CleanXError::ScanAnnule => {
                <i32>::sse_encode(9, serializer);
            }
            crate::error::CleanXError::ScanDejaEnCours => {
                <i32>::sse_encode(10, serializer);
            }
            crate::error::CleanXError::NonSupporte { detail } => {
                <i32>::sse_encode(11, serializer);
                <String>::sse_encode(detail, serializer);
            }
            crate::error::CleanXError::Interne { detail } => {
                <i32>::sse_encode(12, serializer);
                <String>::sse_encode(detail, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::logging::EntreeLog {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.date, serializer);
        <String>::sse_encode(self.niveau, serializer);
        <String>::sse_encode(self.message, serializer);
    }
}

impl SseEncode for crate::api::EvenementMoteur {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::EvenementMoteur::Journal { message } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::EvenementMoteur::Progression {
                scan_id,
                fichier,
                traites,
                total,
            } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(scan_id, serializer);
                <String>::sse_encode(fichier, serializer);
                <u64>::sse_encode(traites, serializer);
                <u64>::sse_encode(total, serializer);
            }
            crate::api::EvenementMoteur::Menace {
                fichier,
                menace,
                action,
                sha256,
            } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(fichier, serializer);
                <String>::sse_encode(menace, serializer);
                <String>::sse_encode(action, serializer);
                <Option<String>>::sse_encode(sha256, serializer);
            }
            crate::api::EvenementMoteur::ScanTermine {
                scan_id,
                total,
                menaces,
                annule,
            } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(scan_id, serializer);
                <u64>::sse_encode(total, serializer);
                <u64>::sse_encode(menaces, serializer);
                <bool>::sse_encode(annule, serializer);
            }
            crate::api::EvenementMoteur::Protection { active } => {
                <i32>::sse_encode(4, serializer);
                <bool>::sse_encode(active, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::quarantine::FichierQuarantaine {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.nom, serializer);
        <String>::sse_encode(self.origine, serializer);
        <String>::sse_encode(self.date, serializer);
        <String>::sse_encode(self.raison, serializer);
        <u8>::sse_encode(self.score, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::logging::EntreeLog> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::logging::EntreeLog>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::quarantine::FichierQuarantaine> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::quarantine::FichierQuarantaine>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::scheduler::Planification> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::scheduler::Planification>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::rootkit::ProcessusAnalyse> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::rootkit::ProcessusAnalyse>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::scheduler::Planification {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.nom, serializer);
        <Vec<String>>::sse_encode(self.racines, serializer);
        <u64>::sse_encode(self.intervalle_secs, serializer);
        <u64>::sse_encode(self.prochaine_exec, serializer);
    }
}

impl SseEncode for crate::rootkit::ProcessusAnalyse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.pid, serializer);
        <String>::sse_encode(self.nom, serializer);
        <Option<String>>::sse_encode(self.exe, serializer);
        <u64>::sse_encode(self.memoire, serializer);
        <Vec<String>>::sse_encode(self.signaux, serializer);
    }
}

impl SseEncode for crate::api::StatutGlobal {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.protection, serializer);
        <u32>::sse_encode(self.signatures, serializer);
        <u64>::sse_encode(self.menaces, serializer);
        <u64>::sse_encode(self.fichiers_analyses, serializer);
        <bool>::sse_encode(self.scan_en_cours, serializer);
        <Vec<String>>::sse_encode(self.dossiers, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::heuristics::VerdictHeuristique {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::heuristics::VerdictHeuristique::Sain => 0,
                crate::heuristics::VerdictHeuristique::Suspect => 1,
                crate::heuristics::VerdictHeuristique::Menace => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
