// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class CleanXError with _$CleanXError implements FrbException {
  const CleanXError._();

  /// Moteur utilisé avant `initialiser`.
  const factory CleanXError.moteurNonInitialise() =
      CleanXError_MoteurNonInitialise;

  /// Fichier introuvable.
  const factory CleanXError.fichierIntrouvable({
    required String chemin,
  }) = CleanXError_FichierIntrouvable;

  /// Accès refusé (droits insuffisants, sandbox mobile, TCC macOS…).
  const factory CleanXError.permissionRefusee({
    required String chemin,
    required String detail,
  }) = CleanXError_PermissionRefusee;

  /// Fichier verrouillé par un autre processus (WouldBlock, partage refusé).
  const factory CleanXError.fichierVerrouille({
    required String chemin,
  }) = CleanXError_FichierVerrouille;

  /// Chemin invalide (non-UTF8, racine inexistante…).
  const factory CleanXError.cheminInvalide({
    required String chemin,
  }) = CleanXError_CheminInvalide;

  /// Base SQLite illisible ou corrompue.
  const factory CleanXError.baseCorrompue({
    required String detail,
  }) = CleanXError_BaseCorrompue;

  /// Échec d'une opération de quarantaine.
  const factory CleanXError.quarantaine({
    required String detail,
  }) = CleanXError_Quarantaine;

  /// Coffre OS inaccessible et aucun repli autorisé (refus explicite).
  const factory CleanXError.coffreIndisponible({
    required String detail,
  }) = CleanXError_CoffreIndisponible;

  /// Échec de la surveillance temps réel.
  const factory CleanXError.surveillance({
    required String detail,
  }) = CleanXError_Surveillance;

  /// Scan interrompu par l'utilisateur (pas une erreur : signal de contrôle).
  const factory CleanXError.scanAnnule() = CleanXError_ScanAnnule;

  /// Scan déjà en cours.
  const factory CleanXError.scanDejaEnCours() = CleanXError_ScanDejaEnCours;

  /// Fonctionnalité non supportée dans cette compilation.
  const factory CleanXError.nonSupporte({
    required String detail,
  }) = CleanXError_NonSupporte;

  /// Erreur interne inattendue (bug : à remonter avec les logs).
  const factory CleanXError.interne({
    required String detail,
  }) = CleanXError_Interne;
}
