// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'error.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'heuristics.dart';
import 'logging.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'quarantine.dart';
import 'rootkit.dart';
import 'scheduler.dart';


                /// Main entrypoint of the Rust API
                class CleanxCore extends BaseEntrypoint<CleanxCoreApi, CleanxCoreApiImpl, CleanxCoreWire> {
                  @internal
                  static final instance = CleanxCore._();

                  CleanxCore._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    CleanxCoreApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required CleanxCoreApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<CleanxCoreApiImpl, CleanxCoreWire> get apiImplConstructor => CleanxCoreApiImpl.new;

                  @override
                  WireConstructor<CleanxCoreWire> get wireConstructor => CleanxCoreWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    
                    
                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.13.0';

                  @override
                  int get rustContentHash => -971652086;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'cleanx_core',
                    ioDirectory: '../core/target/release/',
                    webPrefix: 'pkg/',
                    wasmBindgenName: 'wasm_bindgen',
                  );
                }
                

                abstract class CleanxCoreApi extends BaseApi {
                  Stream<EvenementMoteur> crateApiActiverProtection();

List<String> crateApiAjouterDossier({required String dossier });

PlatformInt64 crateApiAjouterPlanification({required String nom , required List<String> racines , required BigInt intervalleSecs });

AnalyseHeuristique crateApiAnalyserHeuristiqueApi({required String chemin });

List<ProcessusAnalyse> crateApiAnalyserProcessusApi();

bool crateApiArreterScan();

String crateApiCalculerSha256({required String chemin });

String crateApiDeriverCleApi({required String phrase , required String selB64 });

bool crateApiDesactiverProtection();

List<String> crateApiDossiersSurveilles();

String crateApiExporterLogsCsv();

StatutGlobal crateApiInitialiser({required String base });

String crateApiIntegriteBinaire();

void crateApiLibererRessources();

List<String> crateApiLimitesRootkitApi();

List<EntreeLog> crateApiListerLogs({required int limite });

List<Planification> crateApiListerPlanifications();

List<FichierQuarantaine> crateApiListerQuarantaine();

Future<int> crateApiMettreAJourSignatures({required String urlDepot , required String clePubliqueHex });

PlatformInt64 crateApiMettreEnQuarantaine({required String chemin , required String raison });

bool crateApiModeJeu({required bool actif });

bool crateApiModeJeuActif();

void crateApiRestaurerQuarantaine({required PlatformInt64 id , required String destination });

List<String> crateApiRetirerDossier({required String dossier });

Stream<EvenementMoteur> crateApiScanComplet();

Stream<EvenementMoteur> crateApiScanPersonnalise({required List<String> racines });

Stream<EvenementMoteur> crateApiScanRapide();

StatutGlobal crateApiStatut();

void crateApiSupprimerPlanification({required PlatformInt64 id });

void crateApiSupprimerQuarantaine({required PlatformInt64 id });

void crateApiSuspendreScan({required bool suspendre });

bool crateApiVerifierIntegriteApi({String? attendu });

bool crateApiVerifierPaquetApi({required List<int> paquet , required String signatureHex , required String clePubliqueHex });


                }
                

                class CleanxCoreApiImpl extends CleanxCoreApiImplPlatform implements CleanxCoreApi {
                  CleanxCoreApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override Stream<EvenementMoteur> crateApiActiverProtection()  { 
            final sink = RustStreamSink<EvenementMoteur>();
            unawaited(handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_StreamSink_evenement_moteur_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiActiverProtectionConstMeta,
            argValues: [sink],
            apiImpl: this,
        )));
            return sink.stream;
             }


        TaskConstMeta get kCrateApiActiverProtectionConstMeta => const TaskConstMeta(
            debugName: "activer_protection",
            argNames: ["sink"],
        );
        

@override List<String> crateApiAjouterDossier({required String dossier })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(dossier, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiAjouterDossierConstMeta,
            argValues: [dossier],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiAjouterDossierConstMeta => const TaskConstMeta(
            debugName: "ajouter_dossier",
            argNames: ["dossier"],
        );
        

@override PlatformInt64 crateApiAjouterPlanification({required String nom , required List<String> racines , required BigInt intervalleSecs })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(nom, serializer);
sse_encode_list_String(racines, serializer);
sse_encode_u_64(intervalleSecs, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiAjouterPlanificationConstMeta,
            argValues: [nom, racines, intervalleSecs],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiAjouterPlanificationConstMeta => const TaskConstMeta(
            debugName: "ajouter_planification",
            argNames: ["nom", "racines", "intervalleSecs"],
        );
        

@override AnalyseHeuristique crateApiAnalyserHeuristiqueApi({required String chemin })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(chemin, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_analyse_heuristique,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiAnalyserHeuristiqueApiConstMeta,
            argValues: [chemin],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiAnalyserHeuristiqueApiConstMeta => const TaskConstMeta(
            debugName: "analyser_heuristique_api",
            argNames: ["chemin"],
        );
        

@override List<ProcessusAnalyse> crateApiAnalyserProcessusApi()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_processus_analyse,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiAnalyserProcessusApiConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiAnalyserProcessusApiConstMeta => const TaskConstMeta(
            debugName: "analyser_processus_api",
            argNames: [],
        );
        

@override bool crateApiArreterScan()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiArreterScanConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiArreterScanConstMeta => const TaskConstMeta(
            debugName: "arreter_scan",
            argNames: [],
        );
        

@override String crateApiCalculerSha256({required String chemin })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(chemin, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiCalculerSha256ConstMeta,
            argValues: [chemin],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiCalculerSha256ConstMeta => const TaskConstMeta(
            debugName: "calculer_sha256",
            argNames: ["chemin"],
        );
        

@override String crateApiDeriverCleApi({required String phrase , required String selB64 })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(phrase, serializer);
sse_encode_String(selB64, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiDeriverCleApiConstMeta,
            argValues: [phrase, selB64],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiDeriverCleApiConstMeta => const TaskConstMeta(
            debugName: "deriver_cle_api",
            argNames: ["phrase", "selB64"],
        );
        

@override bool crateApiDesactiverProtection()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiDesactiverProtectionConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiDesactiverProtectionConstMeta => const TaskConstMeta(
            debugName: "desactiver_protection",
            argNames: [],
        );
        

@override List<String> crateApiDossiersSurveilles()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiDossiersSurveillesConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiDossiersSurveillesConstMeta => const TaskConstMeta(
            debugName: "dossiers_surveilles",
            argNames: [],
        );
        

@override String crateApiExporterLogsCsv()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiExporterLogsCsvConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiExporterLogsCsvConstMeta => const TaskConstMeta(
            debugName: "exporter_logs_csv",
            argNames: [],
        );
        

@override StatutGlobal crateApiInitialiser({required String base })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(base, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_statut_global,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiInitialiserConstMeta,
            argValues: [base],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiInitialiserConstMeta => const TaskConstMeta(
            debugName: "initialiser",
            argNames: ["base"],
        );
        

@override String crateApiIntegriteBinaire()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiIntegriteBinaireConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiIntegriteBinaireConstMeta => const TaskConstMeta(
            debugName: "integrite_binaire",
            argNames: [],
        );
        

@override void crateApiLibererRessources()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiLibererRessourcesConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiLibererRessourcesConstMeta => const TaskConstMeta(
            debugName: "liberer_ressources",
            argNames: [],
        );
        

@override List<String> crateApiLimitesRootkitApi()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiLimitesRootkitApiConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiLimitesRootkitApiConstMeta => const TaskConstMeta(
            debugName: "limites_rootkit_api",
            argNames: [],
        );
        

@override List<EntreeLog> crateApiListerLogs({required int limite })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_u_32(limite, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_entree_log,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiListerLogsConstMeta,
            argValues: [limite],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiListerLogsConstMeta => const TaskConstMeta(
            debugName: "lister_logs",
            argNames: ["limite"],
        );
        

@override List<Planification> crateApiListerPlanifications()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_planification,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiListerPlanificationsConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiListerPlanificationsConstMeta => const TaskConstMeta(
            debugName: "lister_planifications",
            argNames: [],
        );
        

@override List<FichierQuarantaine> crateApiListerQuarantaine()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_fichier_quarantaine,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiListerQuarantaineConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiListerQuarantaineConstMeta => const TaskConstMeta(
            debugName: "lister_quarantaine",
            argNames: [],
        );
        

@override Future<int> crateApiMettreAJourSignatures({required String urlDepot , required String clePubliqueHex })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(urlDepot, serializer);
sse_encode_String(clePubliqueHex, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiMettreAJourSignaturesConstMeta,
            argValues: [urlDepot, clePubliqueHex],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMettreAJourSignaturesConstMeta => const TaskConstMeta(
            debugName: "mettre_a_jour_signatures",
            argNames: ["urlDepot", "clePubliqueHex"],
        );
        

@override PlatformInt64 crateApiMettreEnQuarantaine({required String chemin , required String raison })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(chemin, serializer);
sse_encode_String(raison, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiMettreEnQuarantaineConstMeta,
            argValues: [chemin, raison],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMettreEnQuarantaineConstMeta => const TaskConstMeta(
            debugName: "mettre_en_quarantaine",
            argNames: ["chemin", "raison"],
        );
        

@override bool crateApiModeJeu({required bool actif })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_bool(actif, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiModeJeuConstMeta,
            argValues: [actif],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiModeJeuConstMeta => const TaskConstMeta(
            debugName: "mode_jeu",
            argNames: ["actif"],
        );
        

@override bool crateApiModeJeuActif()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiModeJeuActifConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiModeJeuActifConstMeta => const TaskConstMeta(
            debugName: "mode_jeu_actif",
            argNames: [],
        );
        

@override void crateApiRestaurerQuarantaine({required PlatformInt64 id , required String destination })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_i_64(id, serializer);
sse_encode_String(destination, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiRestaurerQuarantaineConstMeta,
            argValues: [id, destination],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiRestaurerQuarantaineConstMeta => const TaskConstMeta(
            debugName: "restaurer_quarantaine",
            argNames: ["id", "destination"],
        );
        

@override List<String> crateApiRetirerDossier({required String dossier })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(dossier, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiRetirerDossierConstMeta,
            argValues: [dossier],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiRetirerDossierConstMeta => const TaskConstMeta(
            debugName: "retirer_dossier",
            argNames: ["dossier"],
        );
        

@override Stream<EvenementMoteur> crateApiScanComplet()  { 
            final sink = RustStreamSink<EvenementMoteur>();
            unawaited(handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_StreamSink_evenement_moteur_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiScanCompletConstMeta,
            argValues: [sink],
            apiImpl: this,
        )));
            return sink.stream;
             }


        TaskConstMeta get kCrateApiScanCompletConstMeta => const TaskConstMeta(
            debugName: "scan_complet",
            argNames: ["sink"],
        );
        

@override Stream<EvenementMoteur> crateApiScanPersonnalise({required List<String> racines })  { 
            final sink = RustStreamSink<EvenementMoteur>();
            unawaited(handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_String(racines, serializer);
sse_encode_StreamSink_evenement_moteur_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiScanPersonnaliseConstMeta,
            argValues: [racines, sink],
            apiImpl: this,
        )));
            return sink.stream;
             }


        TaskConstMeta get kCrateApiScanPersonnaliseConstMeta => const TaskConstMeta(
            debugName: "scan_personnalise",
            argNames: ["racines", "sink"],
        );
        

@override Stream<EvenementMoteur> crateApiScanRapide()  { 
            final sink = RustStreamSink<EvenementMoteur>();
            unawaited(handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_StreamSink_evenement_moteur_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiScanRapideConstMeta,
            argValues: [sink],
            apiImpl: this,
        )));
            return sink.stream;
             }


        TaskConstMeta get kCrateApiScanRapideConstMeta => const TaskConstMeta(
            debugName: "scan_rapide",
            argNames: ["sink"],
        );
        

@override StatutGlobal crateApiStatut()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_statut_global,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiStatutConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiStatutConstMeta => const TaskConstMeta(
            debugName: "statut",
            argNames: [],
        );
        

@override void crateApiSupprimerPlanification({required PlatformInt64 id })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_i_64(id, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiSupprimerPlanificationConstMeta,
            argValues: [id],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiSupprimerPlanificationConstMeta => const TaskConstMeta(
            debugName: "supprimer_planification",
            argNames: ["id"],
        );
        

@override void crateApiSupprimerQuarantaine({required PlatformInt64 id })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_i_64(id, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiSupprimerQuarantaineConstMeta,
            argValues: [id],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiSupprimerQuarantaineConstMeta => const TaskConstMeta(
            debugName: "supprimer_quarantaine",
            argNames: ["id"],
        );
        

@override void crateApiSuspendreScan({required bool suspendre })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_bool(suspendre, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiSuspendreScanConstMeta,
            argValues: [suspendre],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiSuspendreScanConstMeta => const TaskConstMeta(
            debugName: "suspendre_scan",
            argNames: ["suspendre"],
        );
        

@override bool crateApiVerifierIntegriteApi({String? attendu })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_opt_String(attendu, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiVerifierIntegriteApiConstMeta,
            argValues: [attendu],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiVerifierIntegriteApiConstMeta => const TaskConstMeta(
            debugName: "verifier_integrite_api",
            argNames: ["attendu"],
        );
        

@override bool crateApiVerifierPaquetApi({required List<int> paquet , required String signatureHex , required String clePubliqueHex })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_prim_u_8_loose(paquet, serializer);
sse_encode_String(signatureHex, serializer);
sse_encode_String(clePubliqueHex, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_clean_x_error,
        )
        ,
            constMeta: kCrateApiVerifierPaquetApiConstMeta,
            argValues: [paquet, signatureHex, clePubliqueHex],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiVerifierPaquetApiConstMeta => const TaskConstMeta(
            debugName: "verifier_paquet_api",
            argNames: ["paquet", "signatureHex", "clePubliqueHex"],
        );
        



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return AnyhowException(raw as String); }

@protected RustStreamSink<EvenementMoteur> dco_decode_StreamSink_evenement_moteur_Sse(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
throw UnimplementedError(); }

@protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected AnalyseHeuristique dco_decode_analyse_heuristique(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
                return AnalyseHeuristique(score: dco_decode_u_8(arr[0]),
signaux: dco_decode_list_String(arr[1]),
verdict: dco_decode_verdict_heuristique(arr[2]),); }

@protected bool dco_decode_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as bool; }

@protected CleanXError dco_decode_clean_x_error(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
switch (raw[0]) {
                case 0: return CleanXError_MoteurNonInitialise();
case 1: return CleanXError_FichierIntrouvable(chemin: dco_decode_String(raw[1]),);
case 2: return CleanXError_PermissionRefusee(chemin: dco_decode_String(raw[1]),detail: dco_decode_String(raw[2]),);
case 3: return CleanXError_FichierVerrouille(chemin: dco_decode_String(raw[1]),);
case 4: return CleanXError_CheminInvalide(chemin: dco_decode_String(raw[1]),);
case 5: return CleanXError_BaseCorrompue(detail: dco_decode_String(raw[1]),);
case 6: return CleanXError_Quarantaine(detail: dco_decode_String(raw[1]),);
case 7: return CleanXError_CoffreIndisponible(detail: dco_decode_String(raw[1]),);
case 8: return CleanXError_Surveillance(detail: dco_decode_String(raw[1]),);
case 9: return CleanXError_ScanAnnule();
case 10: return CleanXError_ScanDejaEnCours();
case 11: return CleanXError_NonSupporte(detail: dco_decode_String(raw[1]),);
case 12: return CleanXError_Interne(detail: dco_decode_String(raw[1]),);
                default: throw Exception("unreachable");
            } }

@protected EntreeLog dco_decode_entree_log(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return EntreeLog(id: dco_decode_i_64(arr[0]),
date: dco_decode_String(arr[1]),
niveau: dco_decode_String(arr[2]),
message: dco_decode_String(arr[3]),); }

@protected EvenementMoteur dco_decode_evenement_moteur(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
switch (raw[0]) {
                case 0: return EvenementMoteur_Journal(message: dco_decode_String(raw[1]),);
case 1: return EvenementMoteur_Progression(scanId: dco_decode_String(raw[1]),fichier: dco_decode_String(raw[2]),traites: dco_decode_u_64(raw[3]),total: dco_decode_u_64(raw[4]),);
case 2: return EvenementMoteur_Menace(fichier: dco_decode_String(raw[1]),menace: dco_decode_String(raw[2]),action: dco_decode_String(raw[3]),sha256: dco_decode_opt_String(raw[4]),);
case 3: return EvenementMoteur_ScanTermine(scanId: dco_decode_String(raw[1]),total: dco_decode_u_64(raw[2]),menaces: dco_decode_u_64(raw[3]),annule: dco_decode_bool(raw[4]),);
case 4: return EvenementMoteur_Protection(active: dco_decode_bool(raw[1]),);
                default: throw Exception("unreachable");
            } }

@protected FichierQuarantaine dco_decode_fichier_quarantaine(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
                return FichierQuarantaine(id: dco_decode_i_64(arr[0]),
nom: dco_decode_String(arr[1]),
origine: dco_decode_String(arr[2]),
date: dco_decode_String(arr[3]),
raison: dco_decode_String(arr[4]),
score: dco_decode_u_8(arr[5]),); }

@protected int dco_decode_i_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected PlatformInt64 dco_decode_i_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeI64(raw); }

@protected List<String> dco_decode_list_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_String).toList(); }

@protected List<EntreeLog> dco_decode_list_entree_log(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_entree_log).toList(); }

@protected List<FichierQuarantaine> dco_decode_list_fichier_quarantaine(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_fichier_quarantaine).toList(); }

@protected List<Planification> dco_decode_list_planification(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_planification).toList(); }

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as List<int>; }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected List<ProcessusAnalyse> dco_decode_list_processus_analyse(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_processus_analyse).toList(); }

@protected String? dco_decode_opt_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_String(raw); }

@protected Planification dco_decode_planification(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
                return Planification(id: dco_decode_i_64(arr[0]),
nom: dco_decode_String(arr[1]),
racines: dco_decode_list_String(arr[2]),
intervalleSecs: dco_decode_u_64(arr[3]),
prochaineExec: dco_decode_u_64(arr[4]),); }

@protected ProcessusAnalyse dco_decode_processus_analyse(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
                return ProcessusAnalyse(pid: dco_decode_u_32(arr[0]),
nom: dco_decode_String(arr[1]),
exe: dco_decode_opt_String(arr[2]),
memoire: dco_decode_u_64(arr[3]),
signaux: dco_decode_list_String(arr[4]),); }

@protected StatutGlobal dco_decode_statut_global(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
                return StatutGlobal(protection: dco_decode_bool(arr[0]),
signatures: dco_decode_u_32(arr[1]),
menaces: dco_decode_u_64(arr[2]),
fichiersAnalyses: dco_decode_u_64(arr[3]),
scanEnCours: dco_decode_bool(arr[4]),
dossiers: dco_decode_list_String(arr[5]),); }

@protected int dco_decode_u_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected BigInt dco_decode_u_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeU64(raw); }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected VerdictHeuristique dco_decode_verdict_heuristique(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return VerdictHeuristique.values[raw as int]; }

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_String(deserializer);
        return AnyhowException(inner); }

@protected RustStreamSink<EvenementMoteur> sse_decode_StreamSink_evenement_moteur_Sse(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
throw UnimplementedError('Unreachable ()'); }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected AnalyseHeuristique sse_decode_analyse_heuristique(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_score = sse_decode_u_8(deserializer);
var var_signaux = sse_decode_list_String(deserializer);
var var_verdict = sse_decode_verdict_heuristique(deserializer);
return AnalyseHeuristique(score: var_score, signaux: var_signaux, verdict: var_verdict); }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected CleanXError sse_decode_clean_x_error(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            var tag_ = sse_decode_i_32(deserializer);
            switch (tag_) { case 0: return CleanXError_MoteurNonInitialise();case 1: var var_chemin = sse_decode_String(deserializer);
return CleanXError_FichierIntrouvable(chemin: var_chemin);case 2: var var_chemin = sse_decode_String(deserializer);
var var_detail = sse_decode_String(deserializer);
return CleanXError_PermissionRefusee(chemin: var_chemin, detail: var_detail);case 3: var var_chemin = sse_decode_String(deserializer);
return CleanXError_FichierVerrouille(chemin: var_chemin);case 4: var var_chemin = sse_decode_String(deserializer);
return CleanXError_CheminInvalide(chemin: var_chemin);case 5: var var_detail = sse_decode_String(deserializer);
return CleanXError_BaseCorrompue(detail: var_detail);case 6: var var_detail = sse_decode_String(deserializer);
return CleanXError_Quarantaine(detail: var_detail);case 7: var var_detail = sse_decode_String(deserializer);
return CleanXError_CoffreIndisponible(detail: var_detail);case 8: var var_detail = sse_decode_String(deserializer);
return CleanXError_Surveillance(detail: var_detail);case 9: return CleanXError_ScanAnnule();case 10: return CleanXError_ScanDejaEnCours();case 11: var var_detail = sse_decode_String(deserializer);
return CleanXError_NonSupporte(detail: var_detail);case 12: var var_detail = sse_decode_String(deserializer);
return CleanXError_Interne(detail: var_detail); default: throw UnimplementedError(''); }
             }

@protected EntreeLog sse_decode_entree_log(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_id = sse_decode_i_64(deserializer);
var var_date = sse_decode_String(deserializer);
var var_niveau = sse_decode_String(deserializer);
var var_message = sse_decode_String(deserializer);
return EntreeLog(id: var_id, date: var_date, niveau: var_niveau, message: var_message); }

@protected EvenementMoteur sse_decode_evenement_moteur(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            var tag_ = sse_decode_i_32(deserializer);
            switch (tag_) { case 0: var var_message = sse_decode_String(deserializer);
return EvenementMoteur_Journal(message: var_message);case 1: var var_scanId = sse_decode_String(deserializer);
var var_fichier = sse_decode_String(deserializer);
var var_traites = sse_decode_u_64(deserializer);
var var_total = sse_decode_u_64(deserializer);
return EvenementMoteur_Progression(scanId: var_scanId, fichier: var_fichier, traites: var_traites, total: var_total);case 2: var var_fichier = sse_decode_String(deserializer);
var var_menace = sse_decode_String(deserializer);
var var_action = sse_decode_String(deserializer);
var var_sha256 = sse_decode_opt_String(deserializer);
return EvenementMoteur_Menace(fichier: var_fichier, menace: var_menace, action: var_action, sha256: var_sha256);case 3: var var_scanId = sse_decode_String(deserializer);
var var_total = sse_decode_u_64(deserializer);
var var_menaces = sse_decode_u_64(deserializer);
var var_annule = sse_decode_bool(deserializer);
return EvenementMoteur_ScanTermine(scanId: var_scanId, total: var_total, menaces: var_menaces, annule: var_annule);case 4: var var_active = sse_decode_bool(deserializer);
return EvenementMoteur_Protection(active: var_active); default: throw UnimplementedError(''); }
             }

@protected FichierQuarantaine sse_decode_fichier_quarantaine(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_id = sse_decode_i_64(deserializer);
var var_nom = sse_decode_String(deserializer);
var var_origine = sse_decode_String(deserializer);
var var_date = sse_decode_String(deserializer);
var var_raison = sse_decode_String(deserializer);
var var_score = sse_decode_u_8(deserializer);
return FichierQuarantaine(id: var_id, nom: var_nom, origine: var_origine, date: var_date, raison: var_raison, score: var_score); }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected PlatformInt64 sse_decode_i_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getPlatformInt64(); }

@protected List<String> sse_decode_list_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <String>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_String(deserializer)); }
        return ans_;
         }

@protected List<EntreeLog> sse_decode_list_entree_log(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <EntreeLog>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_entree_log(deserializer)); }
        return ans_;
         }

@protected List<FichierQuarantaine> sse_decode_list_fichier_quarantaine(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <FichierQuarantaine>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_fichier_quarantaine(deserializer)); }
        return ans_;
         }

@protected List<Planification> sse_decode_list_planification(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <Planification>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_planification(deserializer)); }
        return ans_;
         }

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected List<ProcessusAnalyse> sse_decode_list_processus_analyse(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <ProcessusAnalyse>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_processus_analyse(deserializer)); }
        return ans_;
         }

@protected String? sse_decode_opt_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_String(deserializer));
            } else {
                return null;
            }
             }

@protected Planification sse_decode_planification(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_id = sse_decode_i_64(deserializer);
var var_nom = sse_decode_String(deserializer);
var var_racines = sse_decode_list_String(deserializer);
var var_intervalleSecs = sse_decode_u_64(deserializer);
var var_prochaineExec = sse_decode_u_64(deserializer);
return Planification(id: var_id, nom: var_nom, racines: var_racines, intervalleSecs: var_intervalleSecs, prochaineExec: var_prochaineExec); }

@protected ProcessusAnalyse sse_decode_processus_analyse(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_pid = sse_decode_u_32(deserializer);
var var_nom = sse_decode_String(deserializer);
var var_exe = sse_decode_opt_String(deserializer);
var var_memoire = sse_decode_u_64(deserializer);
var var_signaux = sse_decode_list_String(deserializer);
return ProcessusAnalyse(pid: var_pid, nom: var_nom, exe: var_exe, memoire: var_memoire, signaux: var_signaux); }

@protected StatutGlobal sse_decode_statut_global(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_protection = sse_decode_bool(deserializer);
var var_signatures = sse_decode_u_32(deserializer);
var var_menaces = sse_decode_u_64(deserializer);
var var_fichiersAnalyses = sse_decode_u_64(deserializer);
var var_scanEnCours = sse_decode_bool(deserializer);
var var_dossiers = sse_decode_list_String(deserializer);
return StatutGlobal(protection: var_protection, signatures: var_signatures, menaces: var_menaces, fichiersAnalyses: var_fichiersAnalyses, scanEnCours: var_scanEnCours, dossiers: var_dossiers); }

@protected int sse_decode_u_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint32(); }

@protected BigInt sse_decode_u_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getBigUint64(); }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected VerdictHeuristique sse_decode_verdict_heuristique(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return VerdictHeuristique.values[inner]; }

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.message, serializer); }

@protected void sse_encode_StreamSink_evenement_moteur_Sse(RustStreamSink<EvenementMoteur> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.setupAndSerialize(codec: SseCodec(
            decodeSuccessData: sse_decode_evenement_moteur,
            decodeErrorData: sse_decode_AnyhowException,
        )), serializer); }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_analyse_heuristique(AnalyseHeuristique self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_u_8(self.score, serializer);
sse_encode_list_String(self.signaux, serializer);
sse_encode_verdict_heuristique(self.verdict, serializer);
 }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }

@protected void sse_encode_clean_x_error(CleanXError self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
switch (self) { case CleanXError_MoteurNonInitialise(): sse_encode_i_32(0, serializer); case CleanXError_FichierIntrouvable(chemin: final chemin): sse_encode_i_32(1, serializer); sse_encode_String(chemin, serializer);
case CleanXError_PermissionRefusee(chemin: final chemin,detail: final detail): sse_encode_i_32(2, serializer); sse_encode_String(chemin, serializer);
sse_encode_String(detail, serializer);
case CleanXError_FichierVerrouille(chemin: final chemin): sse_encode_i_32(3, serializer); sse_encode_String(chemin, serializer);
case CleanXError_CheminInvalide(chemin: final chemin): sse_encode_i_32(4, serializer); sse_encode_String(chemin, serializer);
case CleanXError_BaseCorrompue(detail: final detail): sse_encode_i_32(5, serializer); sse_encode_String(detail, serializer);
case CleanXError_Quarantaine(detail: final detail): sse_encode_i_32(6, serializer); sse_encode_String(detail, serializer);
case CleanXError_CoffreIndisponible(detail: final detail): sse_encode_i_32(7, serializer); sse_encode_String(detail, serializer);
case CleanXError_Surveillance(detail: final detail): sse_encode_i_32(8, serializer); sse_encode_String(detail, serializer);
case CleanXError_ScanAnnule(): sse_encode_i_32(9, serializer); case CleanXError_ScanDejaEnCours(): sse_encode_i_32(10, serializer); case CleanXError_NonSupporte(detail: final detail): sse_encode_i_32(11, serializer); sse_encode_String(detail, serializer);
case CleanXError_Interne(detail: final detail): sse_encode_i_32(12, serializer); sse_encode_String(detail, serializer);
  } }

@protected void sse_encode_entree_log(EntreeLog self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_64(self.id, serializer);
sse_encode_String(self.date, serializer);
sse_encode_String(self.niveau, serializer);
sse_encode_String(self.message, serializer);
 }

@protected void sse_encode_evenement_moteur(EvenementMoteur self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
switch (self) { case EvenementMoteur_Journal(message: final message): sse_encode_i_32(0, serializer); sse_encode_String(message, serializer);
case EvenementMoteur_Progression(scanId: final scanId,fichier: final fichier,traites: final traites,total: final total): sse_encode_i_32(1, serializer); sse_encode_String(scanId, serializer);
sse_encode_String(fichier, serializer);
sse_encode_u_64(traites, serializer);
sse_encode_u_64(total, serializer);
case EvenementMoteur_Menace(fichier: final fichier,menace: final menace,action: final action,sha256: final sha256): sse_encode_i_32(2, serializer); sse_encode_String(fichier, serializer);
sse_encode_String(menace, serializer);
sse_encode_String(action, serializer);
sse_encode_opt_String(sha256, serializer);
case EvenementMoteur_ScanTermine(scanId: final scanId,total: final total,menaces: final menaces,annule: final annule): sse_encode_i_32(3, serializer); sse_encode_String(scanId, serializer);
sse_encode_u_64(total, serializer);
sse_encode_u_64(menaces, serializer);
sse_encode_bool(annule, serializer);
case EvenementMoteur_Protection(active: final active): sse_encode_i_32(4, serializer); sse_encode_bool(active, serializer);
  } }

@protected void sse_encode_fichier_quarantaine(FichierQuarantaine self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_64(self.id, serializer);
sse_encode_String(self.nom, serializer);
sse_encode_String(self.origine, serializer);
sse_encode_String(self.date, serializer);
sse_encode_String(self.raison, serializer);
sse_encode_u_8(self.score, serializer);
 }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }

@protected void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putPlatformInt64(self); }

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_String(item, serializer); } }

@protected void sse_encode_list_entree_log(List<EntreeLog> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_entree_log(item, serializer); } }

@protected void sse_encode_list_fichier_quarantaine(List<FichierQuarantaine> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_fichier_quarantaine(item, serializer); } }

@protected void sse_encode_list_planification(List<Planification> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_planification(item, serializer); } }

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self is Uint8List ? self : Uint8List.fromList(self)); }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_list_processus_analyse(List<ProcessusAnalyse> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_processus_analyse(item, serializer); } }

@protected void sse_encode_opt_String(String? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_String(self, serializer);
                }
                 }

@protected void sse_encode_planification(Planification self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_64(self.id, serializer);
sse_encode_String(self.nom, serializer);
sse_encode_list_String(self.racines, serializer);
sse_encode_u_64(self.intervalleSecs, serializer);
sse_encode_u_64(self.prochaineExec, serializer);
 }

@protected void sse_encode_processus_analyse(ProcessusAnalyse self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_u_32(self.pid, serializer);
sse_encode_String(self.nom, serializer);
sse_encode_opt_String(self.exe, serializer);
sse_encode_u_64(self.memoire, serializer);
sse_encode_list_String(self.signaux, serializer);
 }

@protected void sse_encode_statut_global(StatutGlobal self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_bool(self.protection, serializer);
sse_encode_u_32(self.signatures, serializer);
sse_encode_u_64(self.menaces, serializer);
sse_encode_u_64(self.fichiersAnalyses, serializer);
sse_encode_bool(self.scanEnCours, serializer);
sse_encode_list_String(self.dossiers, serializer);
 }

@protected void sse_encode_u_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint32(self); }

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putBigUint64(self); }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_verdict_heuristique(VerdictHeuristique self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }
                }
                
