// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Mode de décision face à une menace (exposé à Dart via FFI).
enum ModeDecision {
  /// Détection + notification uniquement. Aucune action auto. **Défaut.**
  prudent,

  /// Quarantaine automatique si menace avérée (signature connue ou score ≥ 70).
  automatique,

  /// Quarantaine automatique dès score ≥ 50 (suspect inclus). Opt-in confirmé.
  /// Ne supprime JAMAIS : toujours via quarantaine réversible.
  agressif,

  /// Journalise seulement, n'agit pas (ni quarantaine, ni suppression).
  silencieux,
  ;
}
