// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Un processus avec ses signaux de dissimulation.
class ProcessusAnalyse {
  /// PID.
  final int pid;

  /// Nom tel que rapporté (peut être vide = suspect).
  final String nom;

  /// Exécutable résolu, `None` si inaccessible (suspect hors processus système).
  final String? exe;

  /// Mémoire résidente (octets).
  final BigInt memoire;

  /// Raisons de suspicion (vide = rien à signaler).
  final List<String> signaux;

  const ProcessusAnalyse({
    required this.pid,
    required this.nom,
    this.exe,
    required this.memoire,
    required this.signaux,
  });

  @override
  int get hashCode =>
      pid.hashCode ^
      nom.hashCode ^
      exe.hashCode ^
      memoire.hashCode ^
      signaux.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessusAnalyse &&
          runtimeType == other.runtimeType &&
          pid == other.pid &&
          nom == other.nom &&
          exe == other.exe &&
          memoire == other.memoire &&
          signaux == other.signaux;
}
